apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-server
  labels:
    app: cat-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-server
      version: v1
  template:
    metadata:
      labels:
        app: cat-server
        version: v1
    spec:
      containers:
        - name: cat-server
          image: aaronyunan/cat-server:8
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
