apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  gateways:
    - cat-gateway
  hosts:
    - "*"
  http:
    - name: {{ .Chart.Name }}
      match:
        - uri:
            prefix: /{{ .Chart.Name }}
      route:
        - destination:
            host: {{ .Chart.Name }}
            port:
              number: 8080
